[package]
name = "grass-macro-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.grass-macro]
path = "../grass-macro"

[dependencies.grass-runtime]
path = "../grass-runtime"